services:
  api:
    build:
      context: .
      target: runtime
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - network
    profiles:
      - api

  tests:
    build:
      context: .
      target: tests
    container_name: tests
    profiles:
      - tests

networks:
  network:
    driver: bridge
