// <auto-generated />
using System;
using API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Infrastructure.Migrations;

[DbContext(typeof(Context))]
[Migration("20250904174043_InitalCreate")]
partial class InitalCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

        modelBuilder.Entity("API.Domain.Services.Service", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT")
                    .HasColumnName("name");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("services", (string)null);
            });

        modelBuilder.Entity("API.Domain.Services.Service", b =>
            {
                b.OwnsOne("API.Domain.Services.PortRange", "PortRange", b1 =>
                    {
                        b1.Property<Guid>("ServiceId")
                            .HasColumnType("TEXT");

                        b1.Property<ushort>("From")
                            .HasColumnType("INTEGER")
                            .HasColumnName("port_from");

                        b1.Property<ushort>("To")
                            .HasColumnType("INTEGER")
                            .HasColumnName("port_to");

                        b1.HasKey("ServiceId");

                        b1.ToTable("services");

                        b1.WithOwner()
                            .HasForeignKey("ServiceId");
                    });

                b.Navigation("PortRange")
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
